### ISSUE TITLE
[freetype branch] Color Font are Displayed in MonoChrome

### ISSUE THREAD

**Issue by aiekick** [aiekick/ImGuiFontStudio#10]
hello @pshurgal,

sorry for disturb you, you have created a pull request regarding imgui freetype branch for color font.

for have color font support in ImGuiFontStudio i need first to have the ability to laod and display color font.

but he not work. all glyph are displayed in monochrome.

can you check this branch if you have time, maybe im wrong somewhere?
https://github.com/aiekick/ImGuiFontStudio/tree/freetype

Thanks

**Comment by pshurgal** [comment]
Hello, I have just seen you message. Ok, I'l have a look. But first are you sure you are using right font file? As i said in original PR it seems that freetype does not support colors in SVGinOT fonts yet. So you have to check are there `CPAL` and `COLR` tables listed inside your font file. You can just open the font file in HEX editor and look which tables are listed in the beginning of the file.
![image](https://user-images.githubusercontent.com/244044/93570735-22116080-f99c-11ea-9038-3251cb108017.png)

**Comment by aiekick** [comment]
Yep i have checked the font, and there is the tables CPAL and COLR.
i have put a button for switch freetype/imgui rasterizer and activate or not the color.
when i activate color, the smiley was filled in black, and its logic to be filled, sicne this color is layered, but dont understand why no color appearing.
im using the windows font you mention in your PR : C:\Windows\Fonts\seguiemj.ttf

**Comment by pshurgal** [comment]
Ok, I'll have a look

**Comment by aiekick** [comment]
see, what i was talking :
![2020-09-18_12-12-18](https://user-images.githubusercontent.com/1434736/93586245-4ffca200-f9a8-11ea-948e-a3dda148ba16.gif)

you have a windows build here :
https://github.com/aiekick/ImGuiFontStudio/actions/runs/260916146

**Comment by aiekick** [comment]
i though i was just the widget display who was not ok, but when you check the texture, she appears also in two colors : 
![2020-09-18_12-16-16](https://user-images.githubusercontent.com/1434736/93586618-da450600-f9a8-11ea-89d3-c9a88a649c0a.gif)

**Comment by aiekick** [comment]
i found the bug haha. it was not imgui_freetpe :) but my soft

i defined the flag but not pass it to buildatlas.

in fact its weird to have extra_flags in buildatlas func, since flags can be passed directly to  font_config->RasterizerFlags

![ImGuiFontStudio_Msvc_x32_6zBrm4g5lo](https://user-images.githubusercontent.com/1434736/93664848-2f008380-fa72-11ea-9f86-95ed843df6c7.png)

**Comment by pshurgal** [comment]
@aiekick, hello, I have just added a fix into colored glyphs branch which fixes colors and antialiasing https://github.com/pshurgal/imgui/commit/1cc96e735da7367ed8979a288c72123e1ef90017
