### ISSUE TITLE
samples_Fonts share

### ISSUE THREAD

**Issue by mumin16** [aiekick/ImGuiFontStudio#13]
We can share  samples_Fonts in this title?

my archieve is https://github.com/mumin16/GTK-4-Reference-Manual-pdf/blob/main/samples_Fonts.rar

**Comment by aiekick** [comment]
I can add links for font icons yes like i started to do in the wiki . but i will not embed sample fonts in this repo.
If you can make a list of font icon url its cool.
by url, i mean to point on original link (for license term and credits)
