### ISSUE TITLE
Development help?

### ISSUE THREAD

**Issue by dmlo** [aiekick/ImGuiFontStudio#16]
Hi @aiekick,

When I was working on ImGuiFontDialog this morning I have to admit I didn't fully understand what ImGuiFontStudio was. When I mentioned ImGuiCppIcons there I didn't realize that you had this project that does the same thing and so much more. When I saw you had edited that section to mention this project, I took a closer look and wow, this is a really neat project. 

I'm sorry I neglected your project with my edits there! I'm going to send you a fix for that with a better nod to this repo.

Would you mind if hacked around a bit and dropped in some PRs on this project? 

I'd also like to do some work on the file dialog if you're ok with that.

Cheers,

Dan

**Comment by aiekick** [comment]
Hello,

haha np.

yes help is always welcome :) 

thanks for have interest to theses projects :)

**Comment by dmlo** [comment]
I won't be using Dear ImGui in my project for reasons unrelated to your projects. Sorry I won't be able to help.

**Comment by aiekick** [comment]
no problem :)
