### ISSUE TITLE
Not a valid font file ttf error (using Windows release binary)

### ISSUE THREAD

**Issue by moebiussurfing** [aiekick/ImGuiFontStudio#17]
**Describe the bug**
Opening the generated ttf is giving an error.
.h file look fine.
That happened using one only font or/and merging/picking from many fonts.

**Screenshots**
![fonts](https://user-images.githubusercontent.com/2106149/172723767-1d2c75b3-0081-410d-b88c-66e66b2ca39a.PNG)

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Thats the binary that I used:
https://github.com/aiekick/ImGuiFontStudio/releases/download/b0.5/ImGuiFontStudio_Msvc_Win32.exe

Should I compile a new version from the repo by myself?

Thanks!

**Comment by moebiussurfing** [comment]
PS:

Trying to compile here.
I am very newbie out of Visual Studio... 
Any help is appreciated.

1. I am trying to compile on the command prompt but I am getting this error:
```
PS D:\_CODE\_C\ImGuiFontStudio> cmake -B my_build_directory -DCMAKE_BUILD_TYPE=BuildMode
CMake Error: The current CMakeCache.txt directory D:/_CODE/_C/ImGuiFontStudio/my_build_directory/CMakeCache.txt is different than the directory /d/_CODE/_C/ImGuiFontStudio/my_build_directory where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "D:/_CODE/_C/ImGuiFontStudio/CMakeLists.txt" does not match the source "/d/_CODE/_C/ImGuiFontStudio/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
PS D:\_CODE\_C\ImGuiFontStudio> cmake --build my_build_directory --config BuildMode
CMake Error: The current CMakeCache.txt directory D:/_CODE/_C/ImGuiFontStudio/my_build_directory/CMakeCache.txt is different than the directory /d/_CODE/_C/ImGuiFontStudio/my_build_directory where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: /usr/bin/make.exe -f Makefile &&
PS D:\_CODE\_C\ImGuiFontStudio>
```

2. I also tried on MSYS1 32/64 but I am having errors... OpenGL looks that is installed...

```
moebiussurfing@surfingMachine MINGW64 /d/_CODE/_C/ImGuiFontStudio
$ pacman -Ss glew
mingw32/mingw-w64-i686-glew 2.2.0-2 [installed]
    GLEW, The OpenGL Extension Wrangler Library (mingw-w64)
mingw64/mingw-w64-x86_64-glew 2.2.0-2 [installed]
    GLEW, The OpenGL Extension Wrangler Library (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-glew 2.2.0-2
    GLEW, The OpenGL Extension Wrangler Library (mingw-w64)
clang32/mingw-w64-clang-i686-glew 2.2.0-2
    GLEW, The OpenGL Extension Wrangler Library (mingw-w64)
clang64/mingw-w64-clang-x86_64-glew 2.2.0-2
    GLEW, The OpenGL Extension Wrangler Library (mingw-w64)

moebiussurfing@surfingMachine MINGW64 /d/_CODE/_C/ImGuiFontStudio
$ cmake -B my_build_directory -DCMAKE_BUILD_TYPE=BuildMode
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-19044 to use this system, please post your config file on discourse.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please post that file on discourse.cmake.org.
CMake Error at /usr/share/cmake-3.22.1/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.22.1/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22.1/Modules/FindOpenGL.cmake:443 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/3rdparty.cmake:14 (find_package)
  CMakeLists.txt:22 (include)

-- Configuring incomplete, errors occurred!
See also "/d/_CODE/_C/ImGuiFontStudio/my_build_directory/CMakeFiles/CMakeOutput.log".

```

**Comment by moebiussurfing** [comment]
I compiled the current master branch binary,
but still getting the same error...
Any idea?

**Comment by aiekick** [comment]
Hello,
i know there is some problems with some fonts
chek this past issue : #14
the goal of this tool was first for programming and especially for imgui. 
there is better tool for general use, like fontforge.
Not sure why its broken, the generation of font is partial, by ex, i not support composites glyphs and some others features.
this is why there is no release for the moment.

btw you have the code, so you can try to found the bug, because i have no time to work on it for many months.

**Comment by moebiussurfing** [comment]
Ok. thanks.

I tried to open the "broken" ttf and the .h into my ImGui project codes and it worked.
I don't need FontForge at all, or to open the font anywhere else,
I just want to make my ImGui buttons.

![tempsnip](https://user-images.githubusercontent.com/2106149/172961562-0db715d3-536e-4473-9d20-bf466f676520.png)

Now I need to learn a bit to layout fine into the buttons, centered etc..

**Comment by aiekick** [comment]
i think its better to use two font instead of one merged.
because when you merge glyphs, you have source fonts who have differents scale, base line and other things, than can produce different placement of glyphs in the same font. thais is why in ImGuiFontStudio there is a pane for preview the final font for a text.
![image](https://user-images.githubusercontent.com/1434736/173116815-9605a3b0-61ab-44e0-95ee-05e3116f6652.png)

if you merged two font who are using the same params, its ok but if not can be an issue.

for your issue, you need to check the font scale at start
